sudo: required 
services: 
  - docker
before_install: 
  - docker build -t timokito/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true timokito/react-test npm test
after_success: 
  - docker build -t timokito/multi-client ./client
  - docker build -t timokito/multi-nginx ./nginx 
  - docker build -t timokito/multi-server ./server 
  - docker build -t timokito/multi-worker ./worker

  